/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streamer;

import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author Shayanyousefian
 */
public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    public static CustomPlayer player;
    private long timerLastAmount=0;
    private long timerMostCurrent=0;
    private long ms;
    private int progressAmount;
    private Thread progress;
    private Thread timer;
    private static int trackLength;
    private enum modes { play,pause };
    private modes mode;
    private static ArrayList<String> metaData;
    
    public ClientGUI() {
        
        initComponents();
        mode = modes.pause;
        jLabel4.setText(timeFormater(trackLength));
        jLabel7.setText(metaData.get(0));
        jLabel9.setText(metaData.get(1));
        jLabel13.setText(metaData.get(2));
        jLabel10.setText(metaData.get(3));
//        trackLength = player.getMetaLength(1236);
//        Server serv = new Server();
//        serv.streamMetaData();
//        Server.streamAudio();
        //player.play(-1);
        //player.pause();
    }

    public String timeFormater(long millis){
        String mss = String.format("%02d:%02d:%02d",
        TimeUnit.MILLISECONDS.toMinutes(millis) % TimeUnit.HOURS.toMinutes(1),
        TimeUnit.MILLISECONDS.toSeconds(millis) % TimeUnit.MINUTES.toSeconds(1),
        (millis/100)%100);
        return mss;
    }
    public void updateVars() {
        if(mode == modes.play)
            jButton1.setText("Pause");
        else jButton1.setText("Play");
        updateProgress();
        updateTime();
    }
    
    public void updateTime() {
        // Playing
        if(mode == modes.play){
            timer = new Thread(
                new Runnable(){
                    public void run(){
                        try{
                            while(true){
                                ms = timerLastAmount + player.getTime();
                                if(ms>timerMostCurrent) timerMostCurrent = ms;
                                //ms += timerLastAmount;
                                jLabel1.setText(timeFormater(ms));
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, "Error1 displaying time resuming"+ e);
                        }
                    }
                }
            );
            timer.start();
        
        // PAUSING
        }else{
            try{
                timer.stop();
                timer.interrupt();
                timer = null;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error2 timer pausing "+ e);
            }
            System.out.println("timerLastAmount="+timerLastAmount);
            System.out.println("timerMostCurrent="+timerMostCurrent);
            System.out.println("ms="+ms);
            timerLastAmount = ms;
            timerMostCurrent = -1;
        }
    }
    public void updateProgress() {
        // Playing
        System.out.println("ms="+ ms);
        System.out.println("trlength="+ trackLength);
        if(mode == modes.play){
            progress = new Thread(
                new Runnable(){
                    public void run(){
                        try{
                            while(true){
                                progressAmount = (int)(ms*100) / trackLength;
                                jLabel2.setText(String.format("%02d",progressAmount) +"%");
                                jProgressBar1.setValue(progressAmount);
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, "Error1 displaying progress resuming"+ e);
                        }
                    }
                }
            );
            progress.start();
        
        // PAUSING
        }else{
            try{
                progress.stop();
                progress.interrupt();
                progress = null;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error2 progress pausing "+ e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("00:00:00");

        jLabel2.setText("0%");

        jLabel3.setText("/");

        jLabel4.setText("00:00:00");

        jLabel6.setText("Title:");

        jLabel7.setText("Unknown");

        jLabel8.setText("Album:");

        jLabel9.setText("Unknown Album");

        jLabel10.setText("2015");

        jLabel11.setText("Year:");

        jLabel12.setText("Artist:");

        jLabel13.setText("Unknown Artist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(195, 195, 195)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(mode == modes.play) mode = modes.pause;
        else mode = modes.play;
        updateVars();
        if(mode == modes.play) player.resume();
        else player.pause();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        player = new CustomPlayer();
        metaData = player.getMetaData(1236);
        trackLength = Integer.parseInt(metaData.get(4));
      //  player.setPath("/Users/negarbayati/Desktop/still.mp3");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                player = new CustomPlayer();
                new ClientGUI().setVisible(true);
//                player.setPath("/Users/Shayanyousefian/Documents/Eclipse_workspace/Audio-Streamer-Java/still.mp3");
                player.setSocket(1234);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
